package artgame;

/**
 * The enums for the elements names are stored here.
 * @author Group 12
 *
 */
public enum ElementName {
	KENNEDY_SPACE_CENTRE, RS25_LIQUID_ROCKET_ENGINES, INTERIM_CRYOGENIC_PROPULSION_STAGE, HEAT_SHIELD, SERVICE_MODULE,
	LAUNCH_ABORT_SYSTEM, ANNUAL_LEAVE, POWER_AND_PROPULSION_ELEMENT, HABITATION_AND_LOGISTICS_OUTPOST,
	PAYLOAD_AND_RESEARCH_INVESTIGATION, LUNAR_TERRAIN_VEHICLE, POLAR_EXPLORATION_ROVER;
}
